#!/bin/bash

set -e

# . (プロジェクトルート)
# ├── app (アプリケーションリソース)
# │   ├── lib (共通ライブラリ)
# │   │   ├── pom.xml
# │   │   └── src
# │   │       └── ...
# │   ├── web1 (Module: Webアプリケーション1)
# │   │   ├── Dockerfile
# │   │   ├── pom.xml
# │   │   └── src
# │   │       └── ...
# │   ├── web2 (Module: Webアプリケーション2)
# │   │   ├── Dockerfile
# │   │   ├── pom.xml
# │   │   └── src
# │   │       └── ...
# │   └── pom.xml
# └── bootstrap

module_name=$1

# cdk の影響で、docker のビルドコンテキストはモジュールルートにする必要があるので、
# それに合わせて、ローカルのツールでも、モジュールルートに移動してから実行する
cd app

mvn clean package -f ${module_name}/pom.xml

VERSION="0.2"
docker build -t sample-spring-boot-cicd-${module_name} . \
  --build-arg MODULE_NAME=${module_name} \
  --build-arg VERSION=${VERSION} \
  --build-arg COMMIT_ID=${COMMIT_ID}

docker run --rm -it -p 8080:8080 sample-spring-boot-cicd-${module_name}
